# spring-boot-plus Common Config

############################# 访问路径、端口tomcat start #############################
server:
  port: 8181
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
############################# 访问路径、端口tomcat end ###############################

############################### DRUID数据源配置 start ################################
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/cesuan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
############################### DRUID数据源配置 end ################################